### ISSUE TITLE
`NpmRequirement` object has no attribute `_summary`

### ISSUE THREAD

**Issue by WheresHJ** [bartfeenstra/betty#2224] opened 2024-11-27 04:44 UTC
Reporting a bug while running Betty 0.3.15 on Windows 10 for the first time, simply trying to create a new project using the GUI tool. This occurred after clicking 'Save' on the 'Save your new project to...' dialog. Here's the details. Thanks for all the hard work!
```
Traceback (most recent call last):
  File "betty\_npm.py", line 64, in _check
  File "betty\asyncio.py", line 66, in wait_to_thread
  File "betty\asyncio.py", line 94, in return_value
  File "betty\asyncio.py", line 102, in _run
  File "betty\_npm.py", line 42, in npm
  File "betty\subprocess.py", line 54, in run_process
subprocess.CalledProcessError: Command 'npm --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "betty\gui\app.py", line 241, in new_project
  File "betty\gui\project.py", line 685, in __init__
  File "betty\gui\project.py", line 566, in __init__
  File "betty\gui\project.py", line 595, in _set_extension_status
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 148, in is_met
  File "betty\requirement.py", line 148, in 
  File "betty\_npm.py", line 75, in is_met
  File "betty\_npm.py", line 72, in _check
AttributeError: 'NpmRequirement' object has no attribute '_summary'. Did you mean: 'summary'?
Traceback (most recent call last):
  File "betty\_npm.py", line 64, in _check
  File "betty\asyncio.py", line 66, in wait_to_thread
  File "betty\asyncio.py", line 94, in return_value
  File "betty\asyncio.py", line 102, in _run
  File "betty\_npm.py", line 42, in npm
  File "betty\subprocess.py", line 54, in run_process
subprocess.CalledProcessError: Command 'npm --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "betty\gui\app.py", line 241, in new_project
  File "betty\gui\project.py", line 685, in __init__
  File "betty\gui\project.py", line 566, in __init__
  File "betty\gui\project.py", line 595, in _set_extension_status
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 148, in is_met
  File "betty\requirement.py", line 148, in 
  File "betty\_npm.py", line 75, in is_met
  File "betty\_npm.py", line 72, in _check
AttributeError: 'NpmRequirement' object has no attribute '_summary'. Did you mean: 'summary'?
Traceback (most recent call last):
  File "betty\_npm.py", line 64, in _check
  File "betty\asyncio.py", line 66, in wait_to_thread
  File "betty\asyncio.py", line 94, in return_value
  File "betty\asyncio.py", line 102, in _run
  File "betty\_npm.py", line 42, in npm
  File "betty\subprocess.py", line 54, in run_process
subprocess.CalledProcessError: Command 'npm --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "betty\gui\app.py", line 241, in new_project
  File "betty\gui\project.py", line 685, in __init__
  File "betty\gui\project.py", line 566, in __init__
  File "betty\gui\project.py", line 595, in _set_extension_status
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 148, in is_met
  File "betty\requirement.py", line 148, in 
  File "betty\_npm.py", line 75, in is_met
  File "betty\_npm.py", line 72, in _check
AttributeError: 'NpmRequirement' object has no attribute '_summary'. Did you mean: 'summary'?
Traceback (most recent call last):
  File "betty\_npm.py", line 64, in _check
  File "betty\asyncio.py", line 66, in wait_to_thread
  File "betty\asyncio.py", line 94, in return_value
  File "betty\asyncio.py", line 102, in _run
  File "betty\_npm.py", line 42, in npm
  File "betty\subprocess.py", line 54, in run_process
subprocess.CalledProcessError: Command 'npm --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "betty\gui\app.py", line 241, in new_project
  File "betty\gui\project.py", line 685, in __init__
  File "betty\gui\project.py", line 566, in __init__
  File "betty\gui\project.py", line 595, in _set_extension_status
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 166, in is_met
  File "betty\requirement.py", line 166, in 
  File "betty\requirement.py", line 148, in is_met
  File "betty\requirement.py", line 148, in 
  File "betty\_npm.py", line 75, in is_met
  File "betty\_npm.py", line 72, in _check
AttributeError: 'NpmRequirement' object has no attribute '_summary'. Did you mean: 'summary'?
```

**Comment by bartfeenstra** [comment] 2024-11-27 09:53
@WheresHJ Thank you for reporting this! To help us understand the scope of the problem, can you run the command `npm --version` in any terminal/command line and report the output back here?

**Comment by bartfeenstra** [comment] 2024-11-27 13:23
I believe I found the cause. This is fixed in 0.4.x (https://github.com/bartfeenstra/betty/pull/2225) and soon 0.3.x as well (https://github.com/bartfeenstra/betty/pull/2227). I expect to publish new releases for both major versions today or tomorrow.

**Comment by bartfeenstra** [comment] 2024-11-27 14:03
I just released Betty 0.4.0b6 and 0.3.16 which both contain the fix.

With Betty 0.4.0 being scheduled for release in early December, I would suggest you start new projects using the beta. It's got an overall better user experience and 0.3.x no longer receives new features, and will soon stop receiving bug fixes as well.

**Closed as completed by bartfeenstra** 2024-11-27 14:03 UTC
Labels: bug, python

**Comment by WheresHJ** [comment] 2024-11-27 14:10
Awesome, thank you so much! To answer the first question, I don't have NPM installed on this machine (its a personal machine where I'm doing my genealogy work not a dev box). I used the 0.3 version because I didn't see Windows binaries for 0.4 anywhere in the releases list, but maybe I wasn't looking in the right place! Anyway, thanks so much for the work you're doing, can't wait to dig in.

**Comment by bartfeenstra** [comment] 2024-11-27 14:16
The desktop application builds were removed from 0.4 because they proved too high a maintenance burden at this time, so you did see correctly. The documentation site has instructions on how to install Betty if you've already installed Python on your machine.

npm/Node.js is not technically required to run Betty (only for some of the optional extensions), but in practice you'll want it, because some functionality will otherwise be unavailable.
