### ISSUE TITLE
Betty.exe crashes when you try to enter a URL or use the Gramps extension on Windows

### ISSUE THREAD

**Issue by uwagura** [bartfeenstra/betty#1857] opened 2024-08-06 01:38 UTC
When you try to edit the URL field in the gui when running version 0.3.11 of betty.exe on windows, the program crashes without an explanation as to why. The same thing seems to happen when you try to pass a .gramps file to the Gramps tab of the gui. Neither of these problems seem to occur when running `betty gui` from the command line.

**Comment by bartfeenstra** [comment] 2024-08-06 11:59
Thanks for reporting this bug. To help reproduce this problem (needed to work on a fix), can you share step-by-step instructions on what you did from launching the Betty, to it crashing?

**Comment by bartfeenstra** [comment] 2024-08-06 20:15
Also, if you launch betty.exe from a terminal, does it show an error when it crashes?

**Comment by uwagura** [comment] 2024-08-06 22:24
I got the error by simply 
1.) Double clicking on betty.exe after unzipping it from the 0.3.11 version of betty-windows.zip
2.) Clicking on `Create a new project` in the gui that pops up, and creating a new project configuration file in the subsequent window
3.) Moving my cursor to the URL box and trying to edit the default url
The program crashes immediately after step 3. A similar thing happens if you instead go to the gramps tab and try to add a new family tree, only this time it crashes while after you try to upload the file

I tried running betty.exe from powershell, and the same error occurred without any output. Interestingly, the powershell immediately printed a new line after I ran betty.exe, almost as if the program and finished executing before the gui had even popped up.

**Comment by bartfeenstra** [comment] 2024-08-07 13:01
Thanks! I'll try and reproduce this over the coming days.

Please note that the Graphical User Interface/desktop application has been removed from Betty 0.4 (the upcoming version that's scheduled to be released after the summer). This is because it caused significantly more problems than other parts of the code base and there is not enough maintenance capacity. The command line will remain (and has been improved), as well as pretty much else from Betty 0.3.

**Comment by bartfeenstra** [comment] 2024-09-11 16:03
I just tried this on Windows with the official Betty 0.3.13 Windows build, as well as with a custom Betty 0.3.11 build on Linux, and I couldn't reproduce the problem on either platform.

Can you confirm the problem, but **use Betty 0.3.13** to test this again?

**Comment by uwagura** [comment] 2024-09-12 01:26
I did not have this issue with Betty 0.3.13, so I think this issue is resolved. Thanks!

**Comment by bartfeenstra** [comment] 2024-09-12 07:51
@uwagura Thanks for checking! I'll close this bug report then.

**Closed as completed by bartfeenstra** 2024-09-12 07:51 UTC
Labels: bug
